language: elixir
elixir:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
otp_release:
  - 18.0
  - 19.0
  - 20.0
  - 21.0
  - 22.0
env:
  - MIX_ENV=test
matrix:
  allow_failures:
    - otp_release: 18.0
  exclude:
    - elixir: 1.4
      otp_release: 21.0
    - elixir: 1.4
      otp_release: 22.0
    - elixir: 1.5
      otp_release: 21.0
    - elixir: 1.5
      otp_release: 22.0
    - elixir: 1.6
      otp_release: 22.0
    - elixir: 1.8
      otp_release: 19.0
script: mix coveralls.travis
