language: elixir
elixir:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
otp_release:
  - 18.0
  - 19.0
  - 20.0
  - 21.0
env:
  - MIX_ENV=test
matrix:
  exclude:
    - elixir: 1.4
      otp_release: 21.0
    - elixir: 1.5
      otp_release: 21.0
    - elixir: 1.6
      otp_release: 18.0
    - elixir: 1.7
      otp_release: 18.0
script: mix coveralls.travis
